"$schema" = 'https://starship.rs/config-schema.json'

# Starship template for Claude Code statusline

format = """
[](fg:magenta)\
$directory\
[](fg:magenta bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow)\
$line_break $fill $line_break\
[](fg:blue)\
${env_var.CLAUDE_EFFORT}\
${env_var.CLAUDE_MODEL}\
[](fg:blue)\
[](fg:cyan inverted)\
${env_var.CLAUDE_CONTEXT}\
[](fg:cyan) \
${env_var.CLAUDE_RATE_5H} \
${env_var.CLAUDE_RATE_7D}\
"""

add_newline = false

# custom color palette
palette = "everyonelovesyou"

# custom colors
[palettes.everyonelovesyou]
magenta = "purple"

background = "#352727"
foreground = "#fdfdfd"


[fill]
symbol = " "

[directory]
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false
style = "fg:black bg:magenta"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "fg:black bg:yellow"
format = "[ $symbol $branch]($style)"

[git_status]
style = "fg:black bg:yellow"
format = "[[$all_status]($style bold) $ahead_behind]($style)"
ahead = "${count}↑ "
behind = "${count}↓ "
diverged = "${ahead_count}↑ ${behind_count}↓ "
deleted	= ""
modified = "!"
stashed = ""

[env_var.CLAUDE_EFFORT]
style = "fg:black bg:blue"
format = "[$env_value ]($style)"
variable = "CLAUDE_EFFORT"

[env_var.CLAUDE_MODEL]
style = "fg:black bg:blue"
format = "[ $env_value ]($style)"
variable = "CLAUDE_MODEL"

[env_var.CLAUDE_CONTEXT]
style = "fg:black bg:cyan"
format = "[ $env_value ]($style bold)"
variable = "CLAUDE_CONTEXT"

[env_var.CLAUDE_RATE_5H]
symbol = "󰅐 "
style = "fg:foreground dimmed"
format = "[ $symbol$env_value]($style)"
variable = "CLAUDE_RATE_5H"

[env_var.CLAUDE_RATE_7D]
symbol = "󱨴 "
style = "fg:foreground dimmed"
format = "[ $symbol$env_value]($style)"
variable = "CLAUDE_RATE_7D"