"$schema" = "https://starship.rs/config-schema.json"

# Starship template for Claude Code statusline

format = """
${env_var.CLAUDE_MODEL}\
$directory\
$git_branch\
${env_var.CLAUDE_CONTEXT}\
"""

add_newline = false

# custom color palette
palette = "everyonelovesyou"

# custom colors
[palettes.everyonelovesyou]
purple = "#9B5DE5"
pink = "#F47AC6"
yellow = "#FEEB60"
emerald = "#00F5D4"
light_blue = "#00CBFA"

[env_var.CLAUDE_MODEL]
style = "bg:purple"
format = "[\ue0b6](purple)[\u2665  $env_value ]($style)[\ue0b4 ](purple bg:pink)"
variable = "CLAUDE_MODEL"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:pink"
format = "[$path ]($style)[\ue0b0 ](pink bg:yellow)"

[git_branch]
symbol = "\uf418"
style = "bg:yellow"
format = "[$symbol $branch ]($style)[\ue0b0 ](yellow bg:emerald)[\ue0b0](emerald)"

[env_var.CLAUDE_CONTEXT]
style = "bg:light_blue"
format = "[\ue0b0 ](inverted light_blue)[$env_value ]($style bold)[\ue0b0 ](light_blue)"
variable = "CLAUDE_CONTEXT"
